Lendo html
------

In [95]:
import pandas as pd
import numpy as np
#this gives us a list of data frames
movies = pd.read_html('https://en.wikipedia.org/wiki/2016_in_film')
movies[2].head()

      0                           1               2                3
0  Rank                       Title     Distributor  Worldwide gross
1     1  Captain America: Civil War          Disney   $1,153,304,495
2     2                Finding Dory  $1,027,638,154              NaN
3     3                    Zootopia  $1,023,784,195              NaN
4     4             The Jungle Book    $966,550,600              NaN

Vamos pegar um data frame da internet, arrumar e salvar em csv
------

In [96]:
dfm = movies[2]
#primeiro colocamos os nomes nas colunas, mas isso gera o problema de
#tornar a linha 0 redundante
dfm.columns = ['Rank', 'Title', 'Distribution', 'Worldwide gross']
dfm.head()

   Rank                       Title    Distribution  Worldwide gross
0  Rank                       Title     Distributor  Worldwide gross
1     1  Captain America: Civil War          Disney   $1,153,304,495
2     2                Finding Dory  $1,027,638,154              NaN
3     3                    Zootopia  $1,023,784,195              NaN
4     4             The Jungle Book    $966,550,600              NaN

In [97]:
#Usamos o metodo drop para apagar a observacao 0
dfm.drop([0], inplace=True)
dfm.head()

  Rank                       Title    Distribution Worldwide gross
1    1  Captain America: Civil War          Disney  $1,153,304,495
2    2                Finding Dory  $1,027,638,154             NaN
3    3                    Zootopia  $1,023,784,195             NaN
4    4             The Jungle Book    $966,550,600             NaN
5    5     The Secret Life of Pets       Universal    $875,330,302

In [98]:
#Agora vamos usar a coluna Rank para indexar as observacoes.
dfm.index = dfm.Rank
dfm.head()

     Rank                       Title    Distribution Worldwide gross
Rank
1       1  Captain America: Civil War          Disney  $1,153,304,495
2       2                Finding Dory  $1,027,638,154             NaN
3       3                    Zootopia  $1,023,784,195             NaN
4       4             The Jungle Book    $966,550,600             NaN
5       5     The Secret Life of Pets       Universal    $875,330,302

In [99]:
#E assim apagamos a coluna rank
dfm.drop('Rank', 1, inplace=True)
dfm

,Title,Distribution,Worldwide gross
Rank,,,
1,Captain America: Civil War,Disney,"$1,153,304,495"
2,Finding Dory,"$1,027,638,154",NaN
3,Zootopia,"$1,023,784,195",NaN
4,The Jungle Book,"$966,550,600",NaN
5,The Secret Life of Pets,Universal,"$875,330,302"
6,Batman v Superman: Dawn of Justice,Warner Bros.,"$873,260,194"
7,Deadpool,20th Century Fox,"$783,112,979"
8,Suicide Squad,Warner Bros.,"$745,600,054"
9,Fantastic Beasts and Where to Find Them,"$721,605,251",NaN
10,Doctor Strange,Disney,"$654,308,328"

Temos uns erros na tabela. Certos valores estao na coluna errada
olhando a tabela original vemos que a repeticao da companhia
gerou esse problema.

In [100]:
#Vamos por os valores na coluna certa iterando.
for i, corp in enumerate(dfm['Distribution']):
    if '$' in corp:
        dfm['Worldwide gross'][i] = dfm['Distribution'][i]
        dfm['Distribution'][i] = dfm['Distribution'][i-1]
dfm

,Title,Distribution,Worldwide gross
Rank,,,
1,Captain America: Civil War,Disney,"$1,153,304,495"
2,Finding Dory,Disney,"$1,027,638,154"
3,Zootopia,Disney,"$1,023,784,195"
4,The Jungle Book,Disney,"$966,550,600"
5,The Secret Life of Pets,Universal,"$875,330,302"
6,Batman v Superman: Dawn of Justice,Warner Bros.,"$873,260,194"
7,Deadpool,20th Century Fox,"$783,112,979"
8,Suicide Squad,Warner Bros.,"$745,600,054"
9,Fantastic Beasts and Where to Find Them,Warner Bros.,"$721,605,251"
10,Doctor Strange,Disney,"$654,308,328"

In [104]:
#Vamos agora transformar os valores da coluna gross em int.

import string
symbols =',$'
dic_trans = {key: None for key in symbols}
translator = str.maketrans(dic_trans)

for i,value in enumerate(dfm['Worldwide gross']):
    gross_in_number = int(value.translate(translator))
    dfm['Worldwide gross'][i] = gross_in_number
dfm

,Title,Distribution,Worldwide gross
Rank,,,
1,Captain America: Civil War,Disney,1153304495
2,Finding Dory,Disney,1027638154
3,Zootopia,Disney,1023784195
4,The Jungle Book,Disney,966550600
5,The Secret Life of Pets,Universal,875330302
6,Batman v Superman: Dawn of Justice,Warner Bros.,873260194
7,Deadpool,20th Century Fox,783112979
8,Suicide Squad,Warner Bros.,745600054
9,Fantastic Beasts and Where to Find Them,Warner Bros.,721605251
10,Doctor Strange,Disney,654308328

In [136]:
#alterando o nome da coluna para facil acesso
dfm.rename(columns ={'Worldwide gross':'Gross'}, inplace=True)
dfm

                                        Title      Distribution       gross
Rank
1                  Captain America: Civil War            Disney  1153304495
2                                Finding Dory            Disney  1027638154
3                                    Zootopia            Disney  1023784195
4                             The Jungle Book            Disney   966550600
5                     The Secret Life of Pets         Universal   875330302
6          Batman v Superman: Dawn of Justice      Warner Bros.   873260194
7                                    Deadpool  20th Century Fox   783112979
8                               Suicide Squad      Warner Bros.   745600054
9     Fantastic Beasts and Where to Find Them      Warner Bros.   721605251
10                             Doctor Strange            Disney   654308328

In [138]:
#dados basicos
gross = dfm.gross
print('Looking at the highest-grossing films of 2016 \n the mean gross is ${0} and the std is {1}'.\
      format(np.mean(gross),np.std(gross)))

Looking at the highest-grossing films of 2016
 the mean gross is $882449455.2 and the std is 151043229.90337482

In [132]:
dfm.to_csv('2016movies.csv')

In [140]:
data

,user_id,song_id,listen_count,title,artist
0,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOAKIMP12A8C130995,1,The Cove,Jack Johnson
1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBBMDR12A8C13253B,2,Entre Dos Aguas,Paco De Lucia
2,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBXHDL12A81C204C0,1,Stronger,Kanye West
3,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBYHAJ12A6701BF1D,1,Constellations,Jack Johnson
4,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SODACBL12A8C13C273,1,Learn To Fly,Foo Fighters
5,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SODDNQT12A6D4F5F7E,5,Apuesta Por El Rock 'N' Roll,Héroes del Silencio
6,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SODXRTY12AB0180F3B,1,Paper Gangsta,Lady GaGa
7,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOFGUAY12AB017B0A8,1,Stacked Actors,Foo Fighters
8,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOFRQTD12A81C233C0,1,Sehr kosmisch,Harmonia
9,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOHQWYZ12A6D4FA701,1,Heaven's gonna burn your eyes,Thievery Corporation feat. Emiliana Torrini
10,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOIYTOA12A6D4F9A23,1,Let It Be Sung,Jack Johnson / Matt Costa / Zach Gill / Dan Le...
11,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOIZAZL12A6701C53B,5,I'll Be Missing You (Featuring Faith Evans & 1...,Puff Daddy
12,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOJNNUA12A8AE48C7A,1,Love Shack,The B-52's
13,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOJPFQG12A58A7833A,1,Clarity,John Mayer
14,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOKRIMP12A6D4F5DA3,5,I?'m A Steady Rollin? Man,Robert Johnson
15,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOLLGNU12AF72A4D4F,1,The Old Saloon,The Lonely Island
16,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOMGIYR12AB0187973,6,Behind The Sea [Live In Chicago],Panic At The Disco
17,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOMLMKI12A81C204BC,1,Champion,Kanye West
18,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOMSQJY12A8C138539,1,Breakout,Foo Fighters
19,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SONSAEZ12A8C138D7A,1,Ragged Wood,Fleet Foxes
20,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOOKGRB12A8C13CD66,1,Mykonos,Fleet Foxes
21,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOPCVQE12AC468AF36,1,Country Road,Jack Johnson / Paula Fuga
22,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOQIVUD12AB01821D2,1,Oh No,Andrew Bird
23,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOQJLDY12AAF3B456D,1,Love Song For No One,John Mayer
24,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOQLCKR12A81C22440,1,Jewels And Gold,Angus & Julia Stone
25,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SORPMYJ12AF729EB90,1,Warning,Incubus
26,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SORQHCG12A58A7EEBA,1,83,John Mayer
27,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SORUFVF12AB018230B,1,Neon,John Mayer
28,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SORWLTW12A670208FA,1,The Middle,Jimmy Eat World
29,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SORZASF12A6D4F8CFA,2,High and dry,Jorge Drexler
...,...,...,...,...,...
1116579,a955513fb89fdb0d5e8437a5cf8a9b3a0abad4d5,SOWGXOP12A6701E93A,3,Without Me,Eminem
1116580,276e43ad698705e5011e5091f367d951b21246f5,SOAUFOF12AB0180C65,1,Seven Nation Army (Album Version),The White Stripes
1116581,276e43ad698705e5011e5091f367d951b21246f5,SOBJDDA12A6BD53159,1,Long Black Road,Slim Dusty
1116582,276e43ad698705e5011e5091f367d951b21246f5,SOBMKJU12A6D4F7128,5,Nine Times Out Of Ten (1998 Digital Remaster),Cliff Richard & The Shadows
1116583,276e43ad698705e5011e5091f367d951b21246f5,SOBPKPW12A6701E8F9,1,'Till I Collapse,Eminem / Nate Dogg
1116584,276e43ad698705e5011e5091f367d951b21246f5,SODCIML12A6D4FADF9,1,Axel F (Radio Edit),Crazy Frog
1116585,276e43ad698705e5011e5091f367d951b21246f5,SOEOBBM12A8C13570E,1,Vitamin,Incubus
1116586,276e43ad698705e5011e5091f367d951b21246f5,SOGJVUF12A8C141F9F,1,Never Enough,Five Finger Death Punch
1116587,276e43ad698705e5011e5091f367d951b21246f5,SOGLBDH12AB018847B,1,Sinner,Drowning Pool
1116588,276e43ad698705e5011e5091f367d951b21246f5,SOIAUJJ12A58A7FD28,1,Caught In A Mosh,Anthrax
1116589,276e43ad698705e5011e5091f367d951b21246f5,SOIROON12A6701E0B8,1,Black Hole Sun,Soundgarden
1116590,276e43ad698705e5011e5091f367d951b21246f5,SOJYSQP12A8C13EDDF,2,Salvation,Five Finger Death Punch
1116591,276e43ad698705e5011e5091f367d951b21246f5,SOKGMOT12AB018771F,1,Whisper,Evanescence
1116592,276e43ad698705e5011e5091f367d951b21246f5,SOMAKIT12A58A7E292,1,Bodies,Drowning Pool
1116593,276e43ad698705e5011e5091f367d951b21246f5,SOMHTUR12A6D4F8764,4,5.45,Gang Of Four
1116594,276e43ad698705e5011e5091f367d951b21246f5,SOMMUKQ12AB01801A5,1,Burn It To The Ground (Album Version),Nickelback
1116595,276e43ad698705e5011e5091f367d951b21246f5,SOOEEPE12A8AE459A4,1,The Unforgiven III,Metallica
1116596,276e43ad698705e5011e5091f367d951b21246f5,SOOXEIJ12AB0187D16,6,Everybody's Fool (Live in Europe),Evanescence
1116597,276e43ad698705e5011e5091f367d951b21246f5,SORJQJF12AB0184850,1,Open Your Eyes,Alter Bridge
1116598,276e43ad698705e5011e5091f367d951b21246f5,SORTDVT12A8AE46092,2,Raga Haripriya,Pandit Hariprasad Chaurasia
1116599,276e43ad698705e5011e5091f367d951b21246f5,SOSJRJP12A6D4F826F,2,Master Of Puppets,Metallica
1116600,276e43ad698705e5011e5091f367d951b21246f5,SOSKYPY12A8C138198,1,Fall To Pieces,Velvet Revolver
1116601,276e43ad698705e5011e5091f367d951b21246f5,SOSVBPS12A8C141821,1,Something In Your Mouth (Album Version),Nickelback
1116602,276e43ad698705e5011e5091f367d951b21246f5,SOVIMJC12A6D4F92EC,2,No Apologies,Eminem
1116603,276e43ad698705e5011e5091f367d951b21246f5,SOWHYSP12A8C142A21,5,Let's Go [from 'Salvation'],New Order
1116604,276e43ad698705e5011e5091f367d951b21246f5,SOWTYVO12AB0180BDA,8,Surf Wax America,Weezer
1116605,276e43ad698705e5011e5091f367d951b21246f5,SOWZHOY12A6701F9FC,1,Kill The King,Megadeth
1116606,276e43ad698705e5011e5091f367d951b21246f5,SOXJOZW12A6701E90E,7,You Think I Ain't Worth A Dollar_ But I Feel L...,Queens Of The Stone Age
1116607,276e43ad698705e5011e5091f367d951b21246f5,SOXNKNC12A6701F7A8,1,Superbeast,Rob Zombie
1116608,276e43ad698705e5011e5091f367d951b21246f5,SOYRMVO12A6701D106,1,Keep Away,Godsmack